### ISSUE TITLE
Horizontal mode, wrong scroller height

### ISSUE THREAD

**Issue by Diokuz** [Diokuz/baron#123]
Clipper and scroller has non-equal heights, but in webkit they should have equal heights, because of zero-sized native scrollbar.

**Comment by Diokuz** [comment]
The problem was in css
```css
::-webkit-scrollbar {
    width: 0;
}
```
As a result, in horizontal mode native scrollbar was invisible (width 0), but still had a height.

Good CSS:

```css
::-webkit-scrollbar {
    width: 0;
    height: 0;
}
```
